# Site settings
course_name: "DuckAI"
course_semester: "<br /> DuckAI | Hoboken, New Jersey, USA, May 15, 2025"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "duck-ai-stevens.github.io" # the base hostname & protocol for your site

schoolname: "DuckAI Workshop"
schoolurl: "https://www.sigmetrics.org/sigmetrics2025/"
twitter_username:  

address: |
    DuckAI
    DuckAI 2025 Workshop | Hoboken, New Jersey, USA, May 15, 2025

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop', 'vendor']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
